/*

 DUDE.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 16
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
unsigned char dude[] =
{
  0x3C,0x3C,0x42,0x7E,0x81,0xFF,0x81,0xFF,
  0x42,0x00,0x42,0x00,0x24,0x00,0x3C,0x18,
  0x18,0x18,0x18,0x18,0x7E,0x7E,0x18,0x18,
  0x18,0x18,0x24,0x24,0x42,0x42,0x00,0x00
};

/* End of DUDE.C */
